### ISSUE TITLE
error when trying training with custom dataset

### ISSUE THREAD

**Issue by amit154154** [reyllama/mixdl#4]
hello  I am trying train mixdl with custom dataset  I ran this code to prepare the dataset
python3 prepare_data.py --size 128 --out ../pop ../../input/funkopop-humans --n_worker 2

and  this after to train
python3 train_mixdl.py pop  --size 128 --root ../

but it says that 
  File "train_mixdl.py", line 650, in <module>
    train(args, loader, generator, discriminator, extra, g_optim, d_optim, e_optim, g_ema, device)
  File "train_mixdl.py", line 254, in train
    w = torch.matmul(alpha, w) # Form mixup latent codes
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2048x12 and 4x4)

thank you for help (:

**Comment by chaerinkong** [comment]
As the line of code does not depend on the real images, the custom dataset shouldn't be the problem. I assume you are using batch size of 4, but cannot figure out why your w has the size of `2048x12`. Would you try swapping the order of try-except clause in line 249-253, because I sometimes found that the `get_latent` function displays unpredictable behaviors depending on the dependency versions. Please let me know if the problem persists.

**Comment by aminullah6264** [comment]
What is this second dim, shouldn't it be (batch, latent_codes)? could you explain this? thanks

<img width="743" alt="image" src="https://user-images.githubusercontent.com/15268491/220001008-3ce92aea-8322-49d0-b33c-1b5800fa2d74.png">

**Comment by chaerinkong** [comment]
The second dimension corresponds to *styles* in the StyleGAN architecture. (Note that the model employs the extended style space instead of a simple Gaussian latent space, and a 256x256 StyleGAN has 14 layers).
